export const WYPIERDALAJ_Z_TYMI_MAPAMI = {
    "paths":[
       {
          "distance":2100,
          "duration":1860,
          "end_address":"Cygańska Góra 3A, 80-171 Gdańsk, Poland",
          "end_coordinates":{
             "lat":54.3587234,
             "lon":18.6203576
          },
          "start_address":"Traugutta 119, 80-226 Gdańsk, Poland",
          "start_coordinates":{
             "lat":54.36927,
             "lon":18.6074464
          },
          "steps":[
             {
                "distance":11,
                "duration":60,
                "end_coordinates":{
                   "lat":54.369366,
                   "lon":18.6074885
                },
                "instruction":"Head north",
                "start_coordinates":{
                   "lat":54.36927,
                   "lon":18.6074464
                }
             },
             {
                "distance":75,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3693991,
                   "lon":18.6086321
                },
                "instruction":"Turn right toward Traugutta",
                "start_coordinates":{
                   "lat":54.369366,
                   "lon":18.6074885
                }
             },
             {
                "distance":91,
                "duration":60,
                "end_coordinates":{
                   "lat":54.37019890000001,
                   "lon":18.6088618
                },
                "instruction":"Turn left toward Traugutta",
                "start_coordinates":{
                   "lat":54.3693991,
                   "lon":18.6086321
                }
             },
             {
                "distance":100,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3702125,
                   "lon":18.6105354
                },
                "instruction":"Turn right onto Traugutta",
                "start_coordinates":{
                   "lat":54.37019890000001,
                   "lon":18.6088618
                }
             },
             {
                "distance":100,
                "duration":120,
                "end_coordinates":{
                   "lat":54.36919109999999,
                   "lon":18.6103891
                },
                "instruction":"Turn right onto Do Studzienki",
                "start_coordinates":{
                   "lat":54.3702125,
                   "lon":18.6105354
                }
             },
             {
                "distance":17,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3691144,
                   "lon":18.6106193
                },
                "instruction":"Turn left",
                "start_coordinates":{
                   "lat":54.36919109999999,
                   "lon":18.6103891
                }
             },
             {
                "distance":100,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3682944,
                   "lon":18.6108119
                },
                "instruction":"Turn right",
                "start_coordinates":{
                   "lat":54.3691144,
                   "lon":18.6106193
                }
             },
             {
                "distance":200,
                "duration":180,
                "end_coordinates":{
                   "lat":54.3671291,
                   "lon":18.611662
                },
                "instruction":"Turn right",
                "start_coordinates":{
                   "lat":54.3682944,
                   "lon":18.6108119
                }
             },
             {
                "distance":21,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3670967,
                   "lon":18.611978
                },
                "instruction":"Turn left toward Sobieskiego",
                "start_coordinates":{
                   "lat":54.3671291,
                   "lon":18.611662
                }
             },
             {
                "distance":90,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3663125,
                   "lon":18.6116273
                },
                "instruction":"Turn right toward Sobieskiego",
                "start_coordinates":{
                   "lat":54.3670967,
                   "lon":18.611978
                }
             },
             {
                "distance":65,
                "duration":60,
                "end_coordinates":{
                   "lat":54.3661971,
                   "lon":18.6126131
                },
                "instruction":"Turn left toward Sobieskiego",
                "start_coordinates":{
                   "lat":54.3663125,
                   "lon":18.6116273
                }
             },
             {
                "distance":500,
                "duration":480,
                "end_coordinates":{
                   "lat":54.3618169,
                   "lon":18.6111264
                },
                "instruction":"Turn right onto Sobieskiego",
                "start_coordinates":{
                   "lat":54.3661971,
                   "lon":18.6126131
                }
             },
             {
                "distance":500,
                "duration":540,
                "end_coordinates":{
                   "lat":54.35925,
                   "lon":18.6175172
                },
                "instruction":"Turn left onto Nowa Medyków",
                "start_coordinates":{
                   "lat":54.3618169,
                   "lon":18.6111264
                }
             },
             {
                "distance":200,
                "duration":120,
                "end_coordinates":{
                   "lat":54.3587234,
                   "lon":18.6203576
                },
                "instruction":"Continue straight onto Cygańska GóraDestination will be on the right",
                "start_coordinates":{
                   "lat":54.35925,
                   "lon":18.6175172
                }
             }
          ]
       },
       {
          
       }
    ]
 }
